// <auto-generated />
using System;
using Excercise12Garage2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Excercise12Garage2.Migrations
{
    [DbContext(typeof(Excercise12Garage2Context))]
    [Migration("20210315200318_Garage NumberOfParkingPlaces = 10")]
    partial class GarageNumberOfParkingPlaces10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Excercise12Garage2.Models.Garage", b =>
                {
                    b.Property<int>("GaregeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfParkingPlaces")
                        .HasColumnType("int");

                    b.HasKey("GaregeId");

                    b.ToTable("Garage");

                    b.HasData(
                        new
                        {
                            GaregeId = 1,
                            Name = "Group 3. Garage",
                            NumberOfParkingPlaces = 10
                        });
                });

            modelBuilder.Entity("Excercise12Garage2.Models.ParkedVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NumberOfWheels")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckIn = new DateTime(2021, 2, 27, 21, 3, 17, 770, DateTimeKind.Local).AddTicks(3703),
                            Color = "Blue",
                            Make = "Koenigsegg",
                            Model = "CCR",
                            NumberOfWheels = 4,
                            RegistrationNumber = "EKY 055",
                            VehicleType = "Sportscar"
                        },
                        new
                        {
                            Id = 2,
                            CheckIn = new DateTime(2021, 2, 10, 21, 3, 17, 774, DateTimeKind.Local).AddTicks(3235),
                            Color = "silver",
                            Make = "Scania AB",
                            Model = "2017 Scania R Series",
                            NumberOfWheels = 8,
                            RegistrationNumber = "KST 810",
                            VehicleType = "Truck"
                        },
                        new
                        {
                            Id = 3,
                            CheckIn = new DateTime(2021, 2, 23, 21, 3, 17, 774, DateTimeKind.Local).AddTicks(3299),
                            Color = "Green",
                            Make = "Volvo",
                            Model = "2018 D Series",
                            NumberOfWheels = 8,
                            RegistrationNumber = "D 7900",
                            VehicleType = "Bus"
                        },
                        new
                        {
                            Id = 4,
                            CheckIn = new DateTime(2021, 3, 10, 21, 3, 17, 774, DateTimeKind.Local).AddTicks(3318),
                            Color = "Black",
                            Make = "SAAB",
                            Model = "Saab 9000",
                            NumberOfWheels = 4,
                            RegistrationNumber = "H 965",
                            VehicleType = "Boat"
                        },
                        new
                        {
                            Id = 5,
                            CheckIn = new DateTime(2021, 3, 11, 21, 3, 17, 774, DateTimeKind.Local).AddTicks(3338),
                            Color = "Ash",
                            Make = "Husqvarna",
                            Model = "Husqvarna 2020",
                            NumberOfWheels = 2,
                            RegistrationNumber = "H 345",
                            VehicleType = "Motorcycle"
                        },
                        new
                        {
                            Id = 6,
                            CheckIn = new DateTime(2021, 3, 8, 21, 3, 17, 774, DateTimeKind.Local).AddTicks(3352),
                            Color = "White",
                            Make = "SSPA Sweden AB",
                            Model = "SSPA 2019",
                            NumberOfWheels = 2,
                            RegistrationNumber = "IMO 8814275",
                            VehicleType = "Boat"
                        },
                        new
                        {
                            Id = 7,
                            CheckIn = new DateTime(2021, 3, 4, 21, 3, 17, 774, DateTimeKind.Local).AddTicks(3367),
                            Color = "Yellow",
                            Make = "SAS",
                            Model = "Airbus A330",
                            NumberOfWheels = 3,
                            RegistrationNumber = "A330-300",
                            VehicleType = "Airplane"
                        });
                });

            modelBuilder.Entity("Excercise12Garage2.Models.VehicleParkingPlace", b =>
                {
                    b.Property<int>("ParkingPlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GarageGaregeId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailableParkingPlace")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFreeParkingPlace")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHandicapped")
                        .HasColumnType("bit");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("ParkingPlaceId");

                    b.HasIndex("GarageGaregeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleParkingPlace");
                });

            modelBuilder.Entity("Excercise12Garage2.Models.VehicleParkingPlace", b =>
                {
                    b.HasOne("Excercise12Garage2.Models.Garage", null)
                        .WithMany("VehicleParkingPlace")
                        .HasForeignKey("GarageGaregeId");

                    b.HasOne("Excercise12Garage2.Models.ParkedVehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Excercise12Garage2.Models.Garage", b =>
                {
                    b.Navigation("VehicleParkingPlace");
                });
#pragma warning restore 612, 618
        }
    }
}
